### ISSUE TITLE
strange error requiring `cljs.tools.reader`

### ISSUE THREAD

**Issue by jaredly** [Lambda-X/replumb#134] opened 2016-01-21 20:25 UTC
```
Could not parse ns form cljs.tools.reader - No protocol method IDeref.-deref defined for type null:
```
![image](https://cloud.githubusercontent.com/assets/112170/12493022/642b50e2-c040-11e5-814b-44e1feb6c373.png)

I also get this error when trying to require `quil.core` (after I've gotten past the "can't find processingjs" error).

I think it might be related to macros -- b/c subsequent attempts to `require cljs.tools.reader` fail with:
```
No such macros namespace: cljs.tools.reader.reader-types, could not locate cljs/tools/reader/reader_types.clj or cljs/tools/reader/reader_types.cljc
```

![image](https://cloud.githubusercontent.com/assets/112170/12493134/d94d029e-c040-11e5-860c-861f652dd566.png)

It's possible there's a bug in `cljs.analyzer` - the error comes from [here](https://github.com/clojure/clojurescript/blob/master/src/main/clojure/cljs/analyzer.cljc#L1674):

```clojure
(defn check-uses [uses env]
  (doseq [[sym lib] uses]
    (let [js-lib (get-in @env/*compiler* [:js-dependency-index (name lib)])]
      (when (and (= (get-in @env/*compiler* [::namespaces lib :defs sym] ::not-found) ::not-found)
```
the error is that `env/*compiler*` is null, and trying to deref `null` throws. The thing is, the passed in `env` parameter looks like it represents the same thing that `env/*compiler*` -- the `check-uses` call comes from [here](https://github.com/clojure/clojurescript/blob/master/src/main/cljs/cljs/js.cljs#L386) in `js.cljs`, where `env` is defined as `(:*compiler* bound-vars)`, and `bound-vars` originally comes from [here](https://github.com/clojure/clojurescript/blob/master/src/main/cljs/cljs/js.cljs#L213), where `:*compiler*` is `(env/default-compiler-env)`.

but... it's also possible that replumb (or something) is supposed to be `binding` `env/*compiler*` and isn't...

I also don't know how to hack on cljs core, or I would see if there was a simple fix.

Anyway, I just looked, and `planck` doesn't seem to have this problem.
@mfikes do you have any light to shed?

**Comment by arichiardi** [comment] 2016-01-21 20:31
It is unlikely to be a bug in analyzer, probably we are not passing in something.

**Comment by arichiardi** [comment] 2016-01-21 20:33
@jaredly shot in the dark, is `cljs.tools.reader` in `:src-paths`?

**Comment by jaredly** [comment] 2016-01-21 21:42
yup, it is

**Comment by jaredly** [comment] 2016-01-21 21:47
Hmm so it looks like it's not finding `reader_types.clj` (the macros file), and it's true -- the file isn't in `src-paths`. So it's cljs core that moves the files around right? And it makes sense that it would leave out the `.clj(c)` source files -- is there a setting or something to get them in there too? 
![image](https://cloud.githubusercontent.com/assets/112170/12495575/af2db9a6-c04d-11e5-90a3-408a10261aa4.png)

**Comment by arichiardi** [comment] 2016-01-21 22:46
@jaredly I don't know if this is the answer you are looking for, but  I am working on [boot-cljs-src](https://github.com/Lambda-X/boot-cljs-src), which will be a task that will try to collect all the source files you need in order to require to work correctly...

Here your project has a dependency on `tools.reader` but it looks like there is a [source file in `:src-paths`](https://github.com/clojure/tools.reader/tree/master/src/main/cljs/cljs/tools/reader) missing. What this task will do is to fetch these things for you (actually at the moment I am just fetching clojurescript and the closure library. At some point I will deal with the dependencies...If you manually copy the content of [`tools.reader`](https://github.com/clojure/tools.reader/tree/master/src/main) in `:src-paths` it should work.

It is weird that it throws though, maybe there is something else going on...

**Comment by jaredly** [comment] 2016-01-22 00:14
actually the error isn't caused by the missing file -- it doesn't have that error until the *second* time I try the require. here's the output of just the first time

```
Initializing REPL environment with data nil
Discovering goog/deps.js in [/js/main.out /js/main.out]
Calling eval-str on (require (quote [cljs.tools.reader])) with options {:target :default, :read-file-fn! <hidden function>, :src-paths [/js/main.out /js/main.out], :warning-as-error false, :no-pr-str-on-value true, :verbose true, :init-fns <hidden function>, :load-fn! <hidden function>}
Processing :require via (ns cljs.user (:require [cljs.tools.reader]))
Namespace side effects for cljs.user
Loading dependencies for cljs.user
Loading cljs.tools.reader namespace
Reading /js/main.out/cljs/tools/reader.cljs ...
Found valid /js/main.out/goog/deps.js
Evaluating cljs.tools.reader
Namespace side effects for cljs.tools.reader
Loading dependencies for cljs.tools.reader
Loading cljs.tools.reader.reader-types namespace
Reading /js/main.out/cljs/tools/reader/reader_types.cljs ...
Evaluating cljs.tools.reader.reader-types
Namespace side effects for cljs.tools.reader.reader-types
Loading dependencies for cljs.tools.reader.reader-types
Loading cljs.tools.reader.impl.utils namespace
Reading /js/main.out/cljs/tools/reader/impl/utils.cljs ...
Evaluating cljs.tools.reader.impl.utils
Namespace side effects for cljs.tools.reader.impl.utils
Loading dependencies for cljs.tools.reader.impl.utils
Loading clojure.string namespace
Reading /js/main.out/clojure/string.cljs ...
Evaluating clojure.string
Namespace side effects for clojure.string
Loading dependencies for clojure.string
Loading goog.string namespace
Reading /js/main.out/goog/string/string.js ...
Loading dependencies for clojure.string
Loading goog.string.StringBuffer namespace
Reading /js/main.out/goog/string/stringbuffer.js ...
Loading dependencies for clojure.string
Processing :use-macros for clojure.string
Processing :require-macros for clojure.string
goog.provide("clojure.string");

**** [ LOTS OF COMPILED JAVASCRIPT (like a few hundred lines) ] ***

Loading dependencies for cljs.tools.reader.impl.utils
Loading goog.string namespace
Loading dependencies for cljs.tools.reader.impl.utils
Processing :use-macros for cljs.tools.reader.impl.utils
Processing :require-macros for cljs.tools.reader.impl.utils
goog.provide("cljs.tools.reader.impl.utils");

**** [ LOTS OF COMPILED JAVASCRIPT (like a few hundred lines) ] ***

Loading dependencies for cljs.tools.reader.reader-types
Loading goog.string namespace
Loading dependencies for cljs.tools.reader.reader-types
Loading goog.string.StringBuffer namespace
Loading dependencies for cljs.tools.reader.reader-types
Checking uses
Processing :use-macros for cljs.tools.reader.reader-types
Processing :require-macros for cljs.tools.reader.reader-types
goog.provide("cljs.tools.reader.reader_types");

**** [ LOTS OF COMPILED JAVASCRIPT (like a few hundred lines) ] ***

Loading dependencies for cljs.tools.reader
Loading cljs.tools.reader.impl.utils namespace
Loading dependencies for cljs.tools.reader
Loading cljs.tools.reader.impl.commons namespace
Reading /js/main.out/cljs/tools/reader/impl/commons.cljs ...
Evaluating cljs.tools.reader.impl.commons
Namespace side effects for cljs.tools.reader.impl.commons
Loading dependencies for cljs.tools.reader.impl.commons
Loading cljs.tools.reader.reader-types namespace
Loading dependencies for cljs.tools.reader.impl.commons
Loading cljs.tools.reader.impl.utils namespace
Loading dependencies for cljs.tools.reader.impl.commons
Checking uses
Processing :use-macros for cljs.tools.reader.impl.commons
Processing :require-macros for cljs.tools.reader.impl.commons
goog.provide("cljs.tools.reader.impl.commons");

**** [ LOTS OF COMPILED JAVASCRIPT (like a few hundred lines) ] ***

Loading dependencies for cljs.tools.reader
Loading clojure.string namespace
Loading dependencies for cljs.tools.reader
Loading goog.array namespace
Reading /js/main.out/goog/array/array.js ...
Loading dependencies for cljs.tools.reader
Loading goog.string namespace
Loading dependencies for cljs.tools.reader
Loading goog.string.StringBuffer namespace
Loading dependencies for cljs.tools.reader
Checking uses
Calling back!
 {:opts
 {:target :default,
  :read-file-fn! "<hidden function>",
  :src-paths ["/js/main.out" "/js/main.out"],
  :warning-as-error false,
  :no-pr-str-on-value true,
  :verbose true,
  :init-fns "<hidden function>",
  :load-fn! "<hidden function>"},
 :data
 {:form (require '[cljs.tools.reader]),
  :ns cljs.user,
  :target :default,
  :side-effect-fn! "<hidden function>"},
 :res
 {:error
  #error {:message "Could not parse ns form cljs.tools.reader", :data {:tag :cljs/analysis-error}, :cause #object[Error Error: No protocol method IDeref.-deref defined for type null: ]}}}
```

**Comment by arichiardi** [comment] 2016-01-22 00:20
this definitely smells like a bug, is it the same with `0.1.5-SNAPSHOT` ?

**Comment by jaredly** [comment] 2016-01-22 00:21
annnnd curious development: if I put the `.clj` file in the right place, then *the second time I require*, it works, and docs are loaded, and everything! the first time still has that weird error though.
I imagine most of the "lets load this" is superfluous though, b/c all these libraries were already loaded when I opened the page....

**Comment by jaredly** [comment] 2016-01-22 00:22
yup I'm on 0.1.5-SNAPSHOT

**Comment by arichiardi** [comment] 2016-01-22 00:24
let me try to implement a test case, I will get back to you

**Comment by arichiardi** [comment] 2016-01-22 01:45
@jaredly No error in the browser for me, but in `node` very weird stuff going on...

The test is not failing on Jenkins but on my machine in node `0.12.5` I get:
```

Calling back!
 {:opts
 {:target :nodejs,
  :read-file-fn! "<hidden function>",
  :src-paths
  ["dev-resources/private/node/compiled/out"
   "dev-resources/private/test/src/cljs"
   "dev-resources/private/test/src/clj"
   "dev-resources/private/test/src/cljc"],
  :write-file-fn! "<hidden function>",
  :verbose true,
  :init-fns "<hidden function>",
  :load-fn! "<hidden function>"},
 :data
 {:form (require '[cljs.tools.reader :as r]),
  :ns cljs.user,
  :target :nodejs,
  :side-effect-fn! "<hidden function>"},
 :res
 {:error
  #error {:message "ERROR", :data {:tag :cljs/analysis-error}, :cause #object[SyntaxError SyntaxError: Unexpected token )]}}}
```

but with node `4.1.2`:

```
cljs.user=> (require '[cljs.tools.reader :as r])
No such macros namespace: cljs.tools.reader.reader-types, could not locate cljs/tools/reader/reader_types.clj or cljs/tools/reader/reader_types.cljc
```

**Comment by jaredly** [comment] 2016-01-22 02:09
yeah.... maybe some of the issue is that replumb/cljs.js etc *use* cljs.tools.reader, and so re-evaluating it breaks things? it would be cool if cljs allowed you to eval things in a *different* namespace-cluster than the one that is hosting. .. like if you could say "the host `cljs.tools.reader` lives at `host.cljs.tools.reader` and then you have like `env_1.cljs.tools.reader`.

**Comment by jaredly** [comment] 2016-01-22 02:10
another possiblity would be to read + analyze & everything, but *not* eval at the end. b/c the library is already evaluated & everything, we just want the docs & interns &c

**Comment by arichiardi** [comment] 2016-01-22 02:12
Usually `require` and `use` only run once (that's why of `:reload` key) but yes, if you read and analyze then you will have you nice AST full of docstrings :dancers:

**Comment by arichiardi** [comment] 2016-01-22 03:32
After you comment I checked the logs again and the paths seem suspicious:

```
Initializing REPL environment with data nil
Discovering goog/deps.js in [/js/main.out /js/main.out] <- twice , or maybe the point?
```

**Comment by jaredly** [comment] 2016-01-22 03:50
oh yeah. removing the duplicate didn't fix it though

**Comment by arichiardi** [comment] 2016-01-22 04:47
It does so many `Loading cljs.tools.reader namespace`...what are you using for serving the website btw?

**Comment by jaredly** [comment] 2016-01-22 06:00
just boot's built-in `(serve)` task

**Comment by arichiardi** [comment] 2016-02-22 21:04
Maybe there is a bug after all, and probably due to some sync that is not happening when reading the dependencies (from the network).

**Comment by mfikes** [comment] 2016-02-22 22:47
This was occurring in Planck, and the root cause was inadvertently loading this bit of code

https://github.com/clojure/clojurescript/blob/c59e957f6230c07e7a228070dd8eb393d5b8ce40/src/main/clojure/cljs/env.cljc#L39

It is not guarded with `defonce` and if you inadvertently load the JavaScript associated with it, it will `nil` out `cljs.env/*compiler*`.

I ended up hacking Planck to work around it, as the JavaScript was actually already loaded, so it was really just a matter of not letting it be accidentally reloaded. https://github.com/mfikes/planck/issues/225

**Comment by arichiardi** [comment] 2016-02-23 03:32
@jaredly If you want to have a quick try (I cannot because in my case I don't have the error, you just need to add this little piece of code [here](https://github.com/mfikes/planck/commit/425537707ecacce6c6dd34cd8a3a0546ba787eb8) in [here](https://github.com/Lambda-X/replumb/blob/master/src/cljs/replumb/load.cljs#L140).

**Comment by arichiardi** [comment] 2016-03-30 19:20
Closing this for now, feel free to reopen it any time.

**Closed by arichiardi** 2016-03-30 19:20 UTC
Labels: bug, cannot-reproduce
