### ISSUE TITLE
Cannot use google closure libs

### ISSUE THREAD

**Issue by viebel** [Lambda-X/replumb#186] opened 2016-05-21 19:44 UTC
`read-eval-call` fails to import google closure libs.

I've tried this syntax:
```clojure
(ns my.ns (:require [goog.string :as gstring])) (gstring/capitalize "abc") 
```

```clojure
(defn no-op [file-url src-cb]
  (src-cb ""))

(def repl-opts-noop (merge (replumb/options :browser
                                             []
                                             no-op)
                            {:warning-as-error false
                             :context :statement
                             :verbose false}))

(replumb/read-eval-call repl-opts-noop identity "(ns my.ns (:require [goog.string :as gstring])) (gstring/capitalize \"abc\") ")
;=> #error {:message "No such namespace: goog.string, could not locate goog/string.cljs, goog/string.cljc, or Closure namespace \"goog.string\"", :data {:tag :cljs/analysis-error}}}
```

**Comment by arichiardi** [comment] 2016-05-21 22:01
It does import them and you can use them in ClojureScript/JavaScript, but as I told you already once on Slack, require is different. You need to provide the source file and IO.
You cannot pass `""` and `no-op` as `load-file`. It is actually a ClojureScript core requirement. Closing this.

**Closed by arichiardi** 2016-05-21 22:01 UTC

**Comment by viebel** [comment] 2016-05-22 06:00
same bug with `fetch-file!` as provided here [io.cljs](https://github.com/Lambda-X/replumb/blob/ddb3adcaec117ccd401ec898c8918939043dcefe/src/browser/replumb/browser/io.cljs#L4)

**Comment by viebel** [comment] 2016-05-22 06:01
Could you please provide a code example that works fine with goog libs?

**Comment by arichiardi** [comment] 2016-05-22 15:27
I am pretty confident this is not a bug because we have tests against it. So a couple of things (sorry not enough time at the moment) to do:

* read this http://lambdax.io/blog/posts/2015-12-21-cljs-replumb-require.html
* hook `fetch-file!`
* have the Google lib in this source path

For the last task, if you use boot you can use `lambda-x/boot-pack-source` project on GitHub.

**Comment by arichiardi** [comment] 2016-05-23 05:28
Example in the test:

https://github.com/Lambda-X/replumb/blob/master/test/cljs/replumb/require_test.cljs#L271

With options:

https://github.com/Lambda-X/replumb/blob/master/test/browser/replumb/test_env.cljs#L7

**Comment by viebel** [comment] 2016-05-24 17:25
Thanks for the reference.
It works fine now. 
Except that I have to manually import some goog libs inside the code of my project
e.g. 

```clojure
[goog.string.format]
 [goog.date.Interval]
 [goog.date.UtcDateTime]
```

What is the best way to import all the goog libs?

**Comment by arichiardi** [comment] 2016-05-24 17:28
I am glad you solved! If you use `boot`, you can check https://github.com/Lambda-X/boot-pack-source

An example usage is [here](https://github.com/Lambda-X/cljs-repl-web/blob/devel/build.boot#L253)

**Comment by viebel** [comment] 2016-05-24 17:39
I'm not familiar with `boot`.
I use `leiningen`.
What should I do though?

**Comment by arichiardi** [comment] 2016-05-24 17:45
Switch to boot!
I have not had the need to develop a `lein` plugin as `clojurescript.io` is using `boot` but I guess an alternative solution would be to copy the files you need (it can be a lot) on the server under your `src-paths` folder.
I was doing that before coming up with the boot task. Again, this is ClojureScript core and there is nothing we can do about it. Planck does the same, bundling the required files in the executable.
